"use client";
import Image from "next/image";
import {FormEvent,useEffect,useMemo,useState} from "react";
import raw from "./data/programs.json";
type P={id:string;country:string;level:string;program:string;university:string;fee:number;currency:string;duration:string;durationLabel:string;sourceSheet:string};
const programs=raw as P[];
const countries=["Russia","Poland","Mauritius","Malaysia","India","Lithuania","Georgia","Hungary","Uzbekistan","UAE","Bulgaria","France","Greece","Ireland","Germany","Australia","United Kingdom","Canada","Spain"];
const steps=[["01","Tell us about you","Share your interests, academic background, destination and budget."],["02","Explore suitable options","Compare programmes and universities from Strive’s master list."],["03","Prepare your application","Get guidance on documents, statements, deadlines and submission."],["04","Move from offer to visa","Understand your offer and prepare for the student visa process."],["05","Book and depart","Plan your journey and flight with support before departure."]];
const services=[["University placements","Find options that fit your profile, plans and circumstances."],["Application support","Bring every requirement into one manageable process."],["Career guidance","Connect your strengths and ambition to a study path."],["Visa centre","Prepare carefully for each stage of the visa process."],["Flight bookings","Turn an accepted offer into a supported departure plan."]];
const money=(p:P)=>{const n=new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(p.fee);return p.currency==="USD"?`$${n}`:p.currency==="EUR"?`€${n}`:`${n} · currency not stated`};
export default function Home(){
 const [country,setCountry]=useState(""),[query,setQuery]=useState(""),[level,setLevel]=useState(""),[uni,setUni]=useState(""),[visible,setVisible]=useState(12),[login,setLogin]=useState(false),[menu,setMenu]=useState(false),[faq,setFaq]=useState(0);
 useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("seen")),{threshold:.08});document.querySelectorAll("[data-reveal]").forEach(n=>o.observe(n));return()=>o.disconnect()},[]);
 const counts=useMemo(()=>Object.fromEntries(countries.map(c=>[c,programs.filter(p=>p.country===c).length])),[]);
 const unis=useMemo(()=>[...new Set(programs.filter(p=>!country||p.country===country).map(p=>p.university))].sort(),[country]);
 const found=useMemo(()=>programs.filter(p=>(!country||p.country===country)&&(!level||p.level===level)&&(!uni||p.university===uni)&&(!query||`${p.program} ${p.university}`.toLowerCase().includes(query.toLowerCase()))),[country,level,uni,query]);
 const go=(e?:FormEvent)=>{e?.preventDefault();setVisible(12);setTimeout(()=>document.querySelector("#courses")?.scrollIntoView({behavior:"smooth"}),40)};
 const pick=(c:string)=>{setCountry(c);setUni("");go()};
 const faqs=[["Are these fees final?","The figures are copied from Strive’s supplied master file. Fees, exchange rates and intakes can change, so the team will verify the current amount before you apply."],["Can you help me choose a course?","Yes. Strive connects your interests, academic background, budget and career direction to suitable study pathways."],["What if a country has no programmes listed?","Contact the team. The destination remains available for consultation while its programme list is being confirmed."],["Where can I meet the team?","Visit Office 35, 6 Chelmsford Road, Belgravia, Harare, Zimbabwe, or call and WhatsApp 078 858 8061."]];
 return <main>
 <header className="siteHeader"><a className="logo" href="#top"><Image src="/strive-logo.jpeg" width={150} height={82} alt="Strive Africa" priority/></a><nav className="desktopNav"><a href="#courses">Programmes</a><a href="#destinations">Countries</a><a href="#process">How it works</a><a href="#services">Services</a><a href="#contact">Contact</a></nav><div className="headerActions"><button className="loginBtn" onClick={()=>setLogin(true)}>Student login</button><a className="headerCta" href="#matcher">Find my options <span>↗</span></a></div><button className="menuBtn" onClick={()=>setMenu(!menu)}>{menu?"×":"☰"}</button>{menu&&<div className="mobileMenu"><a href="#courses">Programmes</a><a href="#destinations">Countries</a><a href="#process">How it works</a><a href="#services">Services</a></div>}</header>
 <section className="hero" id="top"><div className="heroText" data-reveal><span className="kicker"><i/> STUDY ABROAD SUPPORT · HARARE</span><h1>Find the course.<br/><em>Cross the border.</em></h1><p className="lead">Search {programs.length} programme options across {new Set(programs.map(p=>p.country)).size} detailed destinations—then let Strive guide your application, visa and flight.</p><div className="heroLinks"><a href="#matcher">Search programmes <span>↗</span></a><a href="https://wa.me/263788588061" target="_blank">Talk to a consultant</a></div><div className="supportLine"><b>One guided journey</b><span>Placement</span><span>Application</span><span>Visa</span><span>Flight</span></div></div><div className="heroVisual" data-reveal><Image src="/strive/student-airport.webp" alt="Student preparing to board an international flight" width={1800} height={879} priority/><div className="travelCaption"><span>04 / DEPARTURE</span><b>Your next chapter starts here.</b><small>From accepted offer to the boarding gate.</small></div><div className="routePill"><i/> HARARE <span>→</span> YOUR FUTURE</div></div></section>
 <section className="matcher" id="matcher"><div className="matcherIntro"><span>PROGRAMME FINDER</span><h2>Build your<br/>shortlist.</h2><p>Filter the supplied master list by programme, country, university and level.</p></div><form className="searchForm" onSubmit={go}><label><span>01 / PROGRAMME</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Medicine, business, IT…"/></label><label><span>02 / COUNTRY</span><select value={country} onChange={e=>{setCountry(e.target.value);setUni("")}}><option value="">All countries</option>{countries.map(c=><option key={c}>{c}</option>)}</select></label><label><span>03 / UNIVERSITY</span><select value={uni} onChange={e=>setUni(e.target.value)}><option value="">All universities</option>{unis.map(u=><option key={u}>{u}</option>)}</select></label><label><span>04 / LEVEL</span><select value={level} onChange={e=>setLevel(e.target.value)}><option value="">All levels</option><option>Diploma / Foundation</option><option>Undergraduate</option><option>Postgraduate</option></select></label><button>Search <span>↗</span></button></form></section>
 <section className="catalogue" id="courses"><div className="catalogueHead"><div><span>STRIVE MASTER CATALOGUE</span><h2>{found.length} programmes<br/><em>match your search.</em></h2></div><div className="catalogueNote"><b>{country||"All detailed destinations"}</b><p>Fees come from the supplied master file and must be verified before application.</p><button onClick={()=>{setQuery("");setCountry("");setUni("");setLevel("");setVisible(12)}}>Clear filters</button></div></div>{found.length?<><div className="programGrid">{found.slice(0,visible).map((p,i)=><article className="programCard" key={p.id} data-reveal><div className="programIndex">{String(i+1).padStart(2,"0")} <span>{p.country}</span></div><small>{p.level}</small><h3>{p.program}</h3><p>{p.university}</p><div className="programFoot"><div><span>Tuition fee</span><b>{money(p)}</b></div>{(p.durationLabel||p.duration)&&<div><span>Duration</span><b>{p.durationLabel||p.duration}</b></div>}<a href={`https://wa.me/263788588061?text=${encodeURIComponent(`Hello Strive, I would like to discuss ${p.program} at ${p.university} in ${p.country}.`)}`} target="_blank">Ask Strive ↗</a></div></article>)}</div>{visible<found.length&&<button className="loadMore" onClick={()=>setVisible(v=>v+12)}>Show 12 more <span>{visible} of {found.length}</span></button>}</>:<div className="emptyCountry"><span>CONSULTATION AVAILABLE</span><h3>No verified programme rows are in the master file for {country||"this search"} yet.</h3><p>Strive can still investigate universities and current fees for you.</p><a href="https://wa.me/263788588061" target="_blank">Ask the Strive team ↗</a></div>}</section>
 <section className="process" id="process"><div className="processHead" data-reveal><span>HOW IT WORKS</span><h2>From a search to<br/><em>a boarding pass.</em></h2><p>Strive turns the study-abroad process into steps you can understand and act on.</p></div><div className="consultationStory" data-reveal><div className="storyImage"><Image src="/strive/student-consultation.webp" alt="Student reviewing an application with a consultant" width={1600} height={1024}/></div><div><span>REAL GUIDANCE</span><h3>A catalogue begins the journey. A consultant makes it personal.</h3><p>Bring your results, budget and ambitions. Strive helps organise the route from course choice through departure.</p><a href="https://wa.me/263788588061" target="_blank">Book a conversation ↗</a></div></div><div className="steps">{steps.map((s,i)=><article key={s[1]} data-reveal><b>{s[0]}</b><div><span>{i===0?"BEGIN HERE":i===4?"READY TO GO":"KEEP MOVING"}</span><h3>{s[1]}</h3><p>{s[2]}</p></div><i>↗</i></article>)}</div></section>
 <section className="destinations" id="destinations"><div className="destinationIntro" data-reveal><span>19 STUDY DESTINATIONS</span><h2>The world,<br/>made easier.</h2><p>Pick a country to open its programme catalogue. Orange tiles have verified entries from the supplied master file; outlined tiles are available through consultation.</p><div className="destinationKey"><span><i/> Programmes listed</span><span><i/> Ask Strive</span></div><a href="#matcher">Use all filters ↗</a></div><div className="destinationList">{countries.map((c,i)=><button className={counts[c]?"hasPrograms":"consultOnly"} key={c} onClick={()=>pick(c)} data-reveal><span>{String(i+1).padStart(2,"0")}</span><h3>{c}</h3><p>{counts[c]?`${counts[c]} programmes`:"Consultation"}</p><i>↗</i></button>)}</div></section>
 <section className="services" id="services"><div className="sectionLabel light"><span>STRIVE SUPPORT</span><b>Before, during and after application</b></div><div className="serviceHeadline"><h2>Five services.<br/><em>One connected journey.</em></h2><p>Strive brings your university search, paperwork, preparation and travel into one guided route.</p></div><div className="serviceGrid">{services.map((s,i)=><article key={s[0]} data-reveal><span>0{i+1}</span><small>BEYOND BORDERS</small><h3>{s[0]}</h3><p>{s[1]}</p></article>)}</div></section>
 <section className="faq"><div><span>QUESTIONS, ANSWERED</span><h2>Before you<br/>get started.</h2></div><div className="faqList">{faqs.map((f,i)=><article key={f[0]}><button onClick={()=>setFaq(faq===i?-1:i)}><span>0{i+1}</span><b>{f[0]}</b><i>{faq===i?"−":"+"}</i></button>{faq===i&&<p>{f[1]}</p>}</article>)}</div></section>
 <section className="contact" id="contact"><span>READY WHEN YOU ARE</span><h2>Let’s make your next<br/>step <em>clear.</em></h2><p>Meet the Strive team in Belgravia or start on WhatsApp.</p><div><a href="https://wa.me/263788588061" target="_blank">WhatsApp Strive ↗</a><a href="tel:+263788588061">Call 078 858 8061</a></div></section>
 <footer><div className="footerAbout"><a href="#top"><Image src="/strive-logo.jpeg" width={170} height={92} alt="Strive Africa"/></a><p>Study abroad guidance from first search to final departure.</p></div><div><small>EXPLORE</small><a href="#courses">Programmes & fees</a><a href="#destinations">Countries</a><a href="#process">How it works</a></div><div><small>SERVICES</small><a href="#services">University placement</a><a href="#services">Applications</a><a href="#services">Visa & flights</a></div><div><small>VISIT US</small><p>6 Chelmsford Road, Office 35<br/>Belgravia, Harare, Zimbabwe</p><a href="tel:+263788588061">+263 78 858 8061</a></div><div className="footerBottom"><span>© 2026 Strive Africa</span><a href="#top">Back to top ↑</a></div></footer>
 {login&&<div className="modalWrap" onMouseDown={e=>e.target===e.currentTarget&&setLogin(false)}><div className="modal"><button className="close" onClick={()=>setLogin(false)}>×</button><span>STUDENT PORTAL</span><h2>Welcome back.</h2><p>Track saved options and your application journey.</p><label>Email address<input type="email" placeholder="you@example.com"/></label><label>Password<input type="password" placeholder="••••••••"/></label><button className="modalSubmit" onClick={()=>setLogin(false)}>Continue ↗</button><small>Portal access is currently a preview. Contact Strive to begin.</small></div></div>}
 </main>}
