"use client";
import Image from "next/image";
import { FormEvent, useEffect, useMemo, useState } from "react";

const courses=[
 {name:"Business & Management",level:"Undergraduate",place:"United Kingdom",note:"Build global leadership and commercial skills."},
 {name:"Computer Science",level:"Undergraduate",place:"Canada",note:"Software, data and intelligent systems."},
 {name:"Public Health",level:"Postgraduate",place:"United Kingdom",note:"Create healthier communities at scale."},
 {name:"Engineering",level:"Undergraduate",place:"Australia",note:"Design practical solutions for tomorrow."},
 {name:"Data Science",level:"Postgraduate",place:"United States",note:"Turn complex information into decisions."},
 {name:"International Law",level:"Postgraduate",place:"Europe",note:"Study policy, justice and global systems."}
];
const services=[
 ["01","University placement","A focused shortlist shaped around your goals, grades and preferred destination."],
 ["02","Applications","Clear document support and careful application guidance from start to submission."],
 ["03","Career guidance","Connect your strengths and interests to study paths with long-term potential."],
 ["04","Visa centre","Practical guidance through the visa preparation process and key requirements."],
 ["05","Flight bookings","Plan the final step of your journey with convenient travel booking support."]
];

export default function Home(){
 const [destination,setDestination]=useState(""); const [query,setQuery]=useState(""); const [searched,setSearched]=useState(false); const [login,setLogin]=useState(false); const [menu,setMenu]=useState(false);
 useEffect(()=>{const items=document.querySelectorAll("[data-reveal]");const ob=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("seen")),{threshold:.13});items.forEach(i=>ob.observe(i));return()=>ob.disconnect()},[]);
 const results=useMemo(()=>courses.filter(c=>(!destination||c.place===destination)&&(!query||`${c.name} ${c.note}`.toLowerCase().includes(query.toLowerCase()))),[destination,query]);
 function search(e:FormEvent){e.preventDefault();setSearched(true);setTimeout(()=>document.querySelector("#matches")?.scrollIntoView({behavior:"smooth"}),40)}
 return <main>
  <nav className="nav"><a className="brand" href="#top" aria-label="Strive Africa home"><Image src="/strive-logo.jpeg" width={132} height={72} alt="Strive Beyond Borders" priority/></a><div className="navLinks"><a href="#discover">Discover</a><a href="#journey">How it works</a><a href="#services">Services</a><a href="#contact">Contact</a></div><div className="navActions"><a href="tel:+263788588061">078 858 8061</a><button onClick={()=>setLogin(true)}>Log in <b>↗</b></button></div><button className="menuBtn" aria-label="Toggle menu" onClick={()=>setMenu(!menu)}>{menu?"×":"☰"}</button>{menu&&<div className="mobileMenu"><a href="#discover" onClick={()=>setMenu(false)}>Discover</a><a href="#journey" onClick={()=>setMenu(false)}>How it works</a><a href="#services" onClick={()=>setMenu(false)}>Services</a><button onClick={()=>{setLogin(true);setMenu(false)}}>Student login</button></div>}</nav>
  <section className="hero" id="top"><div className="orbit orbitOne"/><div className="orbit orbitTwo"/><div className="heroCopy"><span className="eyebrow"><i/> Zimbabwe to the world</span><h1>Your future has<br/>no <em>borders.</em></h1><p>Find the right university, understand your options and move from application to arrival—with expert guidance at every turn.</p></div><form className="finder" id="discover" onSubmit={search}><div className="finderTop"><span>01</span><p>START YOUR JOURNEY</p><span>3 MIN</span></div><h2>Where do you want<br/>your story to begin?</h2><label><b>⌖</b><select value={destination} onChange={e=>setDestination(e.target.value)} aria-label="Preferred study destination"><option value="">Choose a destination</option><option>United Kingdom</option><option>Canada</option><option>Australia</option><option>United States</option><option>Europe</option></select><span>⌄</span></label><label><b>⌕</b><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Course of interest" placeholder="What would you like to study?"/></label><button className="primary">Explore my options <b>↗</b></button><small>No pressure. No guesswork. Just a clearer next step.</small></form><div className="scrollCue"><span>SCROLL TO DISCOVER</span><div/></div></section>
  {searched&&<section className="matches" id="matches"><div className="sectionHead"><span>YOUR OPTIONS / {String(results.length).padStart(2,"0")}</span><h2>A clearer place<br/>to <em>begin.</em></h2><p>These sample study areas match your search. Speak with a Strive consultant for verified university availability, entry requirements and fees.</p></div><div className="courseStack">{results.length?results.map((c,i)=><article key={c.name} data-reveal><span>0{i+1}</span><div><small>{c.level} · {c.place}</small><h3>{c.name}</h3><p>{c.note}</p></div><a href="https://wa.me/263788588061" target="_blank">Discuss this path ↗</a></article>):<article className="empty"><div><h3>Let’s widen the search.</h3><p>We could not find that exact sample. A consultant can help you explore more options.</p></div><a href="https://wa.me/263788588061" target="_blank">Ask Strive ↗</a></article>}</div></section>}
  <section className="journey" id="journey"><div className="journeyIntro" data-reveal><span>THE STRIVE ROUTE</span><h2>One journey.<br/><em>Five checkpoints.</em></h2><p>From the first idea to the departure gate, we help you understand what comes next.</p></div><div className="route" data-reveal><div className="routeLine"><i/></div>{["Discover","Shortlist","Apply","Prepare","Depart"].map((x,i)=><div className="stop" key={x}><b>0{i+1}</b><span>{x}</span></div>)}</div></section>
  <section className="services" id="services"><div className="servicesTitle" data-reveal><span>WHAT WE DO</span><h2>Support that moves<br/>with <em>you.</em></h2></div><div className="serviceList">{services.map((s,i)=><article data-reveal key={s[1]}><span>{s[0]}</span><h3>{s[1]}</h3><p>{s[2]}</p><i>↗</i></article>)}</div></section>
  <section className="cta" id="contact"><div className="ctaOrbit"/><span>YOUR NEXT CHAPTER</span><h2>Go beyond<br/><em>borders.</em></h2><p>Start with a conversation at our Belgravia office or message our team directly.</p><div className="ctaActions"><a href="https://wa.me/263788588061" target="_blank">WhatsApp us ↗</a><a href="tel:+263788588061">Call 078 858 8061</a></div></section>
  <footer><a className="footerBrand" href="#top"><Image src="/strive-logo.jpeg" width={150} height={82} alt="Strive Beyond Borders"/></a><div><small>VISIT US</small><p>6 Chelmsford Rd, Office 35<br/>Belgravia, Harare, Zimbabwe</p></div><div><small>CONTACT</small><p><a href="tel:+263788588061">+263 78 858 8061</a><br/><a href="https://wa.me/263788588061">WhatsApp</a></p></div><a className="back" href="#top">Back to top ↑</a></footer>
  {login&&<div className="modal" role="dialog" aria-modal="true" aria-label="Student login"><button className="close" onClick={()=>setLogin(false)} aria-label="Close login">×</button><div className="modalMark">S<span>↑</span></div><span>STUDENT PORTAL</span><h2>Welcome<br/>back.</h2><p>Track your saved study options and application journey.</p><label>Email address<input type="email" placeholder="you@example.com"/></label><label>Password<input type="password" placeholder="••••••••"/></label><button className="primary" onClick={()=>setLogin(false)}>Continue <b>↗</b></button><small>Portal access is a preview. Contact Strive to begin an application.</small></div>}
 </main>
}
