"use client";
import Image from "next/image";
import {FormEvent,useEffect,useMemo,useState} from "react";
import raw from "./data/programs.json";
type P={id:string;country:string;level:string;program:string;university:string;fee:number;currency:string;duration:string;durationLabel:string;sourceSheet:string};
const programs=raw as P[];
const countries=["Russia","Poland","Mauritius","Malaysia","India","Lithuania","Georgia","Hungary","Uzbekistan","UAE","Bulgaria","France","Greece","Ireland","Germany","Australia","United Kingdom","Canada","Spain"];
const steps=[["01","Tell us about you","Share your interests, academic background, destination and budget."],["02","Explore suitable options","Compare programmes and universities from Strive’s master list."],["03","Prepare your application","Get guidance on documents, statements, deadlines and submission."],["04","Move from offer to visa","Understand your offer and prepare for the student visa process."],["05","Book and depart","Plan your journey and flight with support before departure."]];
const services=[
 {title:"University placements",strap:"Find the right university for your future",intro:"We assess your academic results, career interests, budget and personal goals before recommending suitable study options—from Foundation and Certificate routes to Bachelor’s and Master’s programmes.",items:["Reviewing your academic qualifications","Recommending suitable countries and universities","Identifying programmes that match your career goals","Comparing tuition fees, entry requirements and intakes","Exploring alternative pathways where direct entry is unavailable","Helping you make an informed final choice"],close:"Let us help you find the right place to study."},
 {title:"Application support",strap:"Making your university application simple and manageable",intro:"STRIVE Africa guides you through every stage so that your application is complete, accurate and professionally prepared, reducing mistakes and unnecessary delays.",items:["Checking university entry requirements","Reviewing your academic and personal documents","Helping you complete application forms","Assisting with motivation letters and personal statements","Submitting applications to selected institutions","Following up on application progress","Explaining offer letters and admission conditions","Guiding you through tuition and acceptance procedures"],close:"Start your application with professional support."},
 {title:"Career guidance",strap:"Connect your strengths and ambitions to the right study path",intro:"We help you understand your strengths, interests and long-term goals before making an important study decision—whether you know what you want or are still uncertain.",items:["Discussing your interests, abilities and ambitions","Reviewing your academic performance","Identifying suitable career options","Recommending relevant courses and qualifications","Explaining available study pathways","Helping you understand potential career opportunities","Supporting parents and students in making informed decisions"],close:"Your career journey begins with the right decision."},
 {title:"Visa centre",strap:"Prepare confidently for every stage of your visa application",intro:"Visa requirements differ between countries. We provide guidance based on the relevant embassy, immigration authority and institution requirements while the final decision remains with immigration.",items:["Providing a personalised visa-document checklist","Reviewing financial and sponsorship documents","Assisting with visa application forms","Guiding students on medical examinations and police clearances","Supporting document certification and legalisation","Assisting with visa appointment preparation","Conducting interview preparation where required","Reviewing the application before submission","Providing updates and guidance throughout the process"],close:"Prepare your student visa application with confidence."},
 {title:"Flight bookings",strap:"Turn your admission into a supported departure plan",intro:"Once your admission and visa have been secured, we help make your transition from home to your study destination easier and less stressful.",items:["Comparing suitable flight options","Helping you select practical travel dates and routes","Assisting with flight reservations and bookings","Checking university reporting and arrival dates","Providing baggage and travel-document guidance","Preparing a pre-departure checklist","Coordinating airport pickup where available","Supporting accommodation and arrival arrangements","Providing important information about your destination"],close:"Let us help you plan your departure."}
];
const heroImages=[1,6,8,11,13].map(n=>`/strive/journeys/journey-${String(n).padStart(2,"0")}.jpeg`);
const galleryImages=Array.from({length:21},(_,i)=>`/strive/journeys/journey-${String(i+1).padStart(2,"0")}.jpeg`);
const money=(p:P)=>{const n=new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(p.fee);return p.currency==="USD"?`$${n}`:p.currency==="EUR"?`€${n}`:`${n} · currency not stated`};
export default function Home(){
 const [country,setCountry]=useState(""),[query,setQuery]=useState(""),[level,setLevel]=useState(""),[uni,setUni]=useState(""),[visible,setVisible]=useState(20),[menu,setMenu]=useState(false),[faq,setFaq]=useState(0),[heroSlide,setHeroSlide]=useState(0),[serviceOpen,setServiceOpen]=useState<number|null>(null),[leadName,setLeadName]=useState(""),[leadContact,setLeadContact]=useState("");
 useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("seen")),{threshold:.08});document.querySelectorAll("[data-reveal]").forEach(n=>o.observe(n));return()=>o.disconnect()},[]);
 useEffect(()=>{const timer=window.setInterval(()=>setHeroSlide(i=>(i+1)%heroImages.length),4000);return()=>window.clearInterval(timer)},[]);
 const counts=useMemo(()=>Object.fromEntries(countries.map(c=>[c,programs.filter(p=>p.country===c).length])),[]);
 const unis=useMemo(()=>[...new Set(programs.filter(p=>!country||p.country===country).map(p=>p.university))].sort(),[country]);
 const found=useMemo(()=>programs.filter(p=>(!country||p.country===country)&&(!level||p.level===level)&&(!uni||p.university===uni)&&(!query||`${p.program} ${p.university}`.toLowerCase().includes(query.toLowerCase()))),[country,level,uni,query]);
 const go=(e?:FormEvent)=>{e?.preventDefault();setVisible(20);setTimeout(()=>document.querySelector("#courses")?.scrollIntoView({behavior:"smooth"}),40)};
 const pick=(c:string)=>{setCountry(c);setUni("");go()};
 const sendLead=(e:FormEvent)=>{e.preventDefault();const message=`Hello Strive, my name is ${leadName}. Please send me the Beyond Borders study guide and updates. My email or phone is ${leadContact}.`;window.open(`https://wa.me/263716730064?text=${encodeURIComponent(message)}`,"_blank","noopener,noreferrer")};
 const faqs=[["Are these fees final?","The figures are copied from Strive’s supplied master file. Fees, exchange rates and intakes can change, so the team will verify the current amount before you apply."],["Can you help me choose a course?","Yes. Strive connects your interests, academic background, budget and career direction to suitable study pathways."],["What if a country has no programmes listed?","Contact the team. The destination remains available for consultation while its programme list is being confirmed."],["Where can I meet the team?","Visit Office 35, 6 Chelmsford Road, Belgravia, Harare, Zimbabwe, or call and WhatsApp +263 71 673 0064."]];
 return <main>
 <header className="siteHeader"><a className="logo" href="#top"><Image src="/strive-logo.jpeg" width={150} height={82} alt="Strive Africa" priority/></a><nav className="desktopNav"><a href="#courses">Programmes</a><a href="#destinations">Countries</a><a href="#process">How it works</a><a href="#services">Services</a><a href="#contact">Contact</a></nav><div className="headerActions"><a className="headerCta" href="#matcher">Find my options <span>↗</span></a></div><button className="menuBtn" onClick={()=>setMenu(!menu)}>{menu?"×":"☰"}</button>{menu&&<div className="mobileMenu"><a href="#courses">Programmes</a><a href="#destinations">Countries</a><a href="#process">How it works</a><a href="#services">Services</a></div>}</header>
 <section className="hero" id="top"><div className="heroText" data-reveal><span className="kicker"><i/> STUDY ABROAD SUPPORT · HARARE</span><h1>Find the course.<br/><em>Cross the border.</em></h1><p className="lead">Search {programs.length} programme options across {new Set(programs.map(p=>p.country)).size} detailed destinations—then let Strive guide your application, visa and flight.</p><div className="heroLinks"><a href="https://wa.me/263716730064" target="_blank">Talk to us <span>↗</span></a><a href="#matcher">Search programmes</a></div><div className="supportLine"><b>One guided journey</b><span>Placement</span><span>Application</span><span>Visa</span><span>Flight</span></div></div><div className="heroVisual" data-reveal>{heroImages.map((src,i)=><Image className={i===heroSlide?"heroSlide active":"heroSlide"} key={src} src={src} alt={`A real Strive student journey — photograph ${i+1}`} fill priority={i===0} sizes="(max-width: 720px) 100vw, 48vw"/>)}<div className="travelCaption"><span>REAL JOURNEYS · {String(heroSlide+1).padStart(2,"0")} / {String(heroImages.length).padStart(2,"0")}</span><b>They made the journey.</b><small>Real students. Real destinations. New beginnings.</small></div><div className="slideDots">{heroImages.map((_,i)=><button aria-label={`Show journey photograph ${i+1}`} className={i===heroSlide?"active":""} key={i} onClick={()=>setHeroSlide(i)}/>)}</div><div className="routePill"><i/> HARARE <span>→</span> BEYOND BORDERS</div></div></section>
 <section className="matcher" id="matcher"><div className="matcherIntro"><span>PROGRAMME FINDER</span><h2>Build your<br/>shortlist.</h2><p>Filter the supplied master list by programme, country, university and level.</p></div><form className="searchForm" onSubmit={go}><label><span>01 / PROGRAMME</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Medicine, business, IT…"/></label><label><span>02 / COUNTRY</span><select value={country} onChange={e=>{setCountry(e.target.value);setUni("")}}><option value="">All countries</option>{countries.map(c=><option key={c}>{c}</option>)}</select></label><label><span>03 / UNIVERSITY</span><select value={uni} onChange={e=>setUni(e.target.value)}><option value="">All universities</option>{unis.map(u=><option key={u}>{u}</option>)}</select></label><label><span>04 / LEVEL</span><select value={level} onChange={e=>setLevel(e.target.value)}><option value="">All levels</option><option>Diploma / Foundation</option><option>Undergraduate</option><option>Postgraduate</option></select></label><button>Search <span>↗</span></button></form></section>
 <section className="catalogue" id="courses"><div className="catalogueHead"><div><span>STRIVE MASTER CATALOGUE</span><h2>{found.length} programmes<br/><em>match your search.</em></h2></div><div className="catalogueNote"><b>{country||"All detailed destinations"}</b><p>Fees come from the supplied master file and must be verified before application.</p><button onClick={()=>{setQuery("");setCountry("");setUni("");setLevel("");setVisible(20)}}>Clear filters</button></div></div>{found.length?<><div className="programGrid">{found.slice(0,visible).map((p,i)=><article className="programCard seen" key={p.id}><div className="programIndex">{String(i+1).padStart(2,"0")} <span>{p.country}</span></div><small>{p.level}</small><h3>{p.program}</h3><p>{p.university}</p><div className="programFoot"><div><span>Tuition fee</span><b>{money(p)}</b></div>{(p.durationLabel||p.duration)&&<div><span>Duration</span><b>{p.durationLabel||p.duration}</b></div>}<a href={`https://wa.me/263716730064?text=${encodeURIComponent(`Hello Strive, I would like to discuss ${p.program} at ${p.university} in ${p.country}.`)}`} target="_blank">Ask Strive ↗</a></div></article>)}</div><div className="catalogueControls">{visible<found.length&&<button className="loadMore" onClick={()=>setVisible(v=>v+20)}>Show 20 more <span>{Math.min(visible,found.length)} of {found.length}</span></button>}{visible>20&&<button className="showLess" onClick={()=>{setVisible(20);document.querySelector("#courses")?.scrollIntoView({behavior:"smooth"})}}>Close extra programmes ↑</button>}</div></>:<div className="emptyCountry"><span>CONSULTATION AVAILABLE</span><h3>No listed programmes for {country||"this search"} yet.</h3><p>This destination is still available through Strive. Talk to the team and they will investigate suitable universities, programmes and current fees for you.</p><a href="https://wa.me/263716730064" target="_blank">Ask about {country||"my options"} ↗</a></div>}</section>
 <section className="process" id="process"><div className="processHead" data-reveal><span>HOW IT WORKS</span><h2>From a search to<br/><em>a boarding pass.</em></h2><p>Strive turns the study-abroad process into steps you can understand and act on.</p></div><div className="consultationStory" data-reveal><div className="storyImage"><Image src="/strive/student-consultation.webp" alt="Student reviewing an application with a consultant" width={1600} height={1024}/></div><div><span>REAL GUIDANCE</span><h3>A catalogue begins the journey. A consultant makes it personal.</h3><p>Bring your results, budget and ambitions. Strive helps organise the route from course choice through departure.</p><a href="https://wa.me/263716730064" target="_blank">Book a conversation ↗</a></div></div><div className="steps">{steps.map((s,i)=><article key={s[1]} data-reveal><b>{s[0]}</b><div><span>{i===0?"BEGIN HERE":i===4?"READY TO GO":"KEEP MOVING"}</span><h3>{s[1]}</h3><p>{s[2]}</p></div><i>↗</i></article>)}</div></section>
 <section className="destinations" id="destinations"><div className="destinationIntro" data-reveal><span>19 STUDY DESTINATIONS</span><h2>The world,<br/>made easier.</h2><p>Pick a country to open its programme catalogue. Orange tiles have verified entries from the supplied master file; outlined tiles are available through consultation.</p><div className="destinationKey"><span><i/> Programmes listed</span><span><i/> Ask Strive</span></div><a href="#matcher">Use all filters ↗</a></div><div className="destinationList">{countries.map((c,i)=><button className={counts[c]?"hasPrograms":"consultOnly"} key={c} onClick={()=>pick(c)} data-reveal><span>{String(i+1).padStart(2,"0")}</span><h3>{c}</h3><p>{counts[c]?`${counts[c]} programmes`:"Consultation"}</p><i>↗</i></button>)}</div></section>
 <section className="services" id="services"><div className="sectionLabel light"><span>STRIVE SUPPORT</span><b>Before, during and after application</b></div><div className="serviceHeadline"><h2>Five services.<br/><em>One connected journey.</em></h2><p>Strive brings your university search, paperwork, preparation and travel into one guided route. Open any service to see exactly how we help.</p></div><div className="serviceGrid">{services.map((s,i)=><button key={s.title} data-reveal onClick={()=>setServiceOpen(i)}><span>0{i+1}</span><small>BEYOND BORDERS</small><h3>{s.title}</h3><p>{s.strap}</p><b>More info ↗</b></button>)}</div></section>
 <section className="journeyGallery" id="gallery"><div className="galleryHead" data-reveal><span>REAL STRIVE JOURNEYS</span><h2>From saying goodbye<br/>to settling in.</h2><p>These are real moments shared from student journeys—departures, arrivals, campuses and life beyond borders.</p></div><div className="galleryTrack">{galleryImages.map((src,i)=><figure key={src} className={i%5===0?"wide":""} data-reveal><Image src={src} alt={`A real Strive student journey — photograph ${i+1}`} fill sizes="(max-width: 720px) 78vw, 28vw"/><figcaption><span>{String(i+1).padStart(2,"0")}</span> Beyond Borders</figcaption></figure>)}</div></section>
 <section className="journal" id="journal"><div className="journalTitle" data-reveal><span>THE BEYOND BORDERS JOURNAL</span><h2>Useful before<br/>you even apply.</h2><p>Short, practical guidance for students and families planning an international education.</p></div><div className="journalStories"><article data-reveal><small>CHOOSING WELL · 5 MIN</small><h3>Choose a university by fit—not only by country.</h3><p>A clear way to compare programme relevance, entry requirements, tuition, location and long-term opportunity.</p><a href="#matcher">Explore your options ↗</a></article><article data-reveal><small>APPLICATIONS · 4 MIN</small><h3>The documents worth preparing early.</h3><p>Start organising results, identification, financial information and supporting documents before deadlines arrive.</p><a href="#process">See the journey ↗</a></article><article data-reveal><small>PRE-DEPARTURE · 6 MIN</small><h3>From offer letter to boarding gate.</h3><p>What happens after admission: acceptance, visa preparation, travel planning and arriving ready.</p><a href="#services">See Strive support ↗</a></article></div><form className="leadCapture" onSubmit={sendLead} data-reveal><div><span>FREE STUDY GUIDE + USEFUL UPDATES</span><h3>Stay one step ahead.</h3><p>Leave your details and continue on WhatsApp to request the guide. Your information is sent to Strive only when you choose to send the message.</p></div><label><span>Your name</span><input required value={leadName} onChange={e=>setLeadName(e.target.value)} placeholder="First and last name"/></label><label><span>Email or phone</span><input required value={leadContact} onChange={e=>setLeadContact(e.target.value)} placeholder="How should we reach you?"/></label><button>Request the guide ↗</button></form></section>
 <section className="studentVoices"><div className="voicesImage" data-reveal><Image src="/strive/journeys/journey-03.jpeg" alt="Students celebrating an academic milestone" fill sizes="(max-width: 720px) 100vw, 50vw"/></div><div className="voicesCopy" data-reveal><span>STUDENT VOICES</span><h2>Real reviews.<br/>No made-up stories.</h2><p>We only publish feedback received from actual Strive students. If Strive helped with your study journey, share what the experience was really like and the team can add your verified review here.</p><a href={`https://wa.me/263716730064?text=${encodeURIComponent("Hello Strive, I would like to share a review of my student journey with you.")}`} target="_blank">Share your Strive review ↗</a><small>Student identity and wording will be confirmed before publication.</small></div></section>
 <section className="faq"><div><span>QUESTIONS, ANSWERED</span><h2>Before you<br/>get started.</h2></div><div className="faqList">{faqs.map((f,i)=><article key={f[0]}><button onClick={()=>setFaq(faq===i?-1:i)}><span>0{i+1}</span><b>{f[0]}</b><i>{faq===i?"−":"+"}</i></button>{faq===i&&<p>{f[1]}</p>}</article>)}</div></section>
 <section className="contact" id="contact"><span>READY WHEN YOU ARE</span><h2>Let’s make your next<br/>step <em>clear.</em></h2><p>Meet the Strive team in Belgravia or start on WhatsApp.</p><div><a href="https://wa.me/263716730064" target="_blank">WhatsApp Strive ↗</a><a href="tel:+263716730064">Call +263 71 673 0064</a></div></section>
 <footer><div className="footerAbout"><a href="#top"><Image src="/strive-logo.jpeg" width={170} height={92} alt="Strive Africa"/></a><p>Study abroad guidance from first search to final departure.</p></div><div><small>EXPLORE</small><a href="#courses">Programmes & fees</a><a href="#destinations">Countries</a><a href="#gallery">Student journeys</a></div><div><small>SERVICES</small><a href="#services">University placement</a><a href="#services">Applications</a><a href="#services">Visa & flights</a></div><div><small>VISIT US</small><p>6 Chelmsford Road, Office 35<br/>Belgravia, Harare, Zimbabwe</p><a href="tel:+263716730064">+263 71 673 0064</a></div><div className="footerBottom"><span>© 2026 Strive Africa</span><a href="#top">Back to top ↑</a></div></footer>
 {serviceOpen!==null&&<div className="serviceModalWrap" onMouseDown={e=>e.target===e.currentTarget&&setServiceOpen(null)}><article className="serviceModal" role="dialog" aria-modal="true" aria-labelledby="service-title"><button className="close" onClick={()=>setServiceOpen(null)} aria-label="Close service details">×</button><span>0{serviceOpen+1} / STRIVE SUPPORT</span><h2 id="service-title">{services[serviceOpen].title}</h2><h3>{services[serviceOpen].strap}</h3><p>{services[serviceOpen].intro}</p><small>OUR SUPPORT INCLUDES</small><ul>{services[serviceOpen].items.map(item=><li key={item}><i>✓</i>{item}</li>)}</ul><b>{services[serviceOpen].close}</b><a href="https://wa.me/263716730064" target="_blank">Talk to us about this service ↗</a></article></div>}
 <a className="whatsappFloat" href="https://wa.me/263716730064" target="_blank" aria-label="Ask Strive anything on WhatsApp"><i>WA</i><span><b>Ask anything</b><small>Contact us for help</small></span></a>
 </main>}
